import { Router } from 'express';
import { google } from 'googleapis';
import { createClient } from '@supabase/supabase-js';
const router = Router();
let supabase;
function getSupabase() { if (!supabase) supabase = createClient(process.env.SUPABASE_URL, process.env.SUPABASE_SERVICE_KEY); return supabase; }
export const ROOMS = [{ id: 'sala-reuniones', name: 'Sala de Reuniones' }, { id: 'sala-multiuso', name: 'Sala Multiuso' }];
function isBlocked(roomId, startTime) { if (roomId !== 'sala-multiuso') return false; const [h, m] = startTime.split(':').map(Number); return h * 60 + m >= 780 && h * 60 + m < 870; }
function requireAuth(req, res, next) { if (!req.session.user) return res.status(401).json({ error: 'Not authenticated' }); next(); }
async function addToGoogleCalendar(tokens, booking) { const auth = new google.auth.OAuth2(process.env.GOOGLE_CLIENT_ID, process.env.GOOGLE_CLIENT_SECRET); auth.setCredentials(tokens); const calendar = google.calendar({ version: 'v3', auth }); const [year, month, day] = booking.date.split('-').map(Number); const [sh, sm] = booking.start_time.split(':').map(Number); const [eh, em] = booking.end_time.split(':').map(Number); const event = await calendar.events.insert({ calendarId: 'primary', requestBody: { summary: `[${booking.room_name}] ${booking.title}`, description: `Reservado por ${booking.user_name} via Sistema de Salas`, start: { dateTime: new Date(year, month-1, day, sh, sm).toISOString(), timeZone: 'America/Argentina/Buenos_Aires' }, end: { dateTime: new Date(year, month-1, day, eh, em).toISOString(), timeZone: 'America/Argentina/Buenos_Aires' } } }); return event.data.id; }
async function addToOutlookCalendar(accessToken, booking) { const [year, month, day] = booking.date.split('-').map(Number); const [sh, sm] = booking.start_time.split(':').map(Number); const [eh, em] = booking.end_time.split(':').map(Number); const res = await fetch('https://graph.microsoft.com/v1.0/me/events', { method: 'POST', headers: { Authorization: `Bearer ${accessToken}`, 'Content-Type': 'application/json' }, body: JSON.stringify({ subject: `[${booking.room_name}] ${booking.title}`, body: { contentType: 'Text', content: `Reservado por ${booking.user_name}` }, start: { dateTime: new Date(year, month-1, day, sh, sm).toISOString(), timeZone: 'America/Argentina/Buenos_Aires' }, end: { dateTime: new Date(year, month-1, day, eh, em).toISOString(), timeZone: 'America/Argentina/Buenos_Aires' } }) }); const data = await res.json(); return data.id; }
async function deleteCalendarEvent(user, calendarEventId) { if (!calendarEventId) return; if (user.provider === 'google') { const auth = new google.auth.OAuth2(process.env.GOOGLE_CLIENT_ID, process.env.GOOGLE_CLIENT_SECRET); auth.setCredentials(user.tokens); const calendar = google.calendar({ version: 'v3', auth }); await calendar.events.delete({ calendarId: 'primary', eventId: calendarEventId }).catch(() => {}); } else { await fetch(`https://graph.microsoft.com/v1.0/me/events/${calendarEventId}`, { method: 'DELETE', headers: { Authorization: `Bearer ${user.tokens.access_token}` } }).catch(() => {}); } }
router.get('/', requireAuth, async (req, res) => { const { date } = req.query; if (!date) return res.status(400).json({ error: 'date required' }); const { data, error } = await getSupabase().from('bookings').select('*').eq('date', date).order('start_time'); if (error) return res.status(500).json({ error: error.message }); res.json(data); });
router.post('/', requireAuth, async (req, res) => { const { room_id, date, start_time, end_time, title } = req.body; const user = req.session.user; if (!room_id || !date || !start_time || !end_time) return res.status(400).json({ error: 'Missing fields' }); const room = ROOMS.find(r => r.id === room_id); if (!room) return res.status(400).json({ error: 'Invalid room' }); if (isBlocked(room_id, start_time)) return res.status(400).json({ error: 'Slot not available' }); const { data: conflicts } = await getSupabase().from('bookings').select('id').eq('room_id', room_id).eq('date', date).lt('start_time', end_time).gt('end_time', start_time); if (conflicts && conflicts.length > 0) return res.status(409).json({ error: 'Slot already booked' }); const booking = { room_id, room_name: room.name, date, start_time, end_time, title: title || 'Reunión', user_name: user.name, user_email: user.email, calendar_event_id: null }; try { if (user.provider === 'google') booking.calendar_event_id = await addToGoogleCalendar(user.tokens, booking); else booking.calendar_event_id = await addToOutlookCalendar(user.tokens.access_token, booking); } catch (e) { console.error('Calendar sync failed:', e.message); } const { data, error } = await getSupabase().from('bookings').insert(booking).select().single(); if (error) { console.error('Supabase insert error:', error.message, error.code); return res.status(500).json({ error: error.message }); } res.status(201).json(data); });
router.delete('/:id', requireAuth, async (req, res) => { const user = req.session.user; const { data: booking, error: fetchError } = await getSupabase().from('bookings').select('*').eq('id', req.params.id).single(); if (fetchError || !booking) return res.status(404).json({ error: 'Not found' }); if (booking.user_email !== user.email) return res.status(403).json({ error: 'Forbidden' }); await deleteCalendarEvent(user, booking.calendar_event_id); const { error } = await getSupabase().from('bookings').delete().eq('id', req.params.id); if (error) return res.status(500).json({ error: error.message }); res.json({ ok: true }); });
export default router;
